import descriptions from './terms/descriptions';

export const terms: Record<string, string> = {
  Lisbon: '里斯本',
  Seville: '塞维尔',
  Istanbul: '伊斯坦堡',
  Barcelona: '巴塞隆纳',
  Algiers: '阿尔及耳',
  Tunis: '突尼斯',
  Valencia: '瓦伦西亚',
  Marseille: '马赛',
  Genoa: '热那亚',
  Pisa: '比萨',
  Naples: '那不勒斯',
  Syracuse: '锡腊库扎',
  Palma: '帕尔马',
  Venice: '威尼斯',
  Ragusa: '拉古萨',
  Candia: '干地亚',
  Athens: '雅典',
  Salonika: '萨罗尼加',
  Alexandria: '亚力山卓',
  Jaffa: '雅法',
  Beirut: '贝鲁特',
  Nicosia: '尼科西亚',
  Tripoli: '的黎波里',
  Kaffa: '卡法',
  Azov: '特纳',
  Trebizond: '特拉比松',
  Ceuta: '休达',
  Bordeaux: '波尔多',
  Nantes: '南特',
  London: '伦敦',
  Bristol: '布里斯托尔',
  Dublin: '都柏林',
  Antwerp: '安特卫普',
  Amsterdam: '阿姆斯特丹',
  Copenhagen: '哥本哈根',
  Hamburg: '汉堡',
  Oslo: '奥斯陆',
  Stockholm: '斯德哥尔摩',
  Lubeck: '吕贝克',
  Danzig: '格但斯克',
  Riga: '里加',
  Bergen: '卑尔根',
  Caracas: '加拉卡斯',
  Cartegena: '喀他基那',
  Havana: '哈瓦那',
  Margarita: '马加里塔',
  Panama: '巴拿马城',
  'Porto Velho': '波鲁特内罗',
  'Santo Domingo': '圣多明尼各',
  Veracruz: '委拉克路斯',
  Jamaica: '牙买加',
  Guatemala: '瓜地马拉',
  Pernambuco: '伯南布哥',
  'Rio de Janeiro': '里约热内卢',
  Maracaibo: '马拉开波',
  Santiago: '圣地亚哥',
  Cayenne: '开云',
  Madeira: '马德拉韦',
  'Santa Cruz': '圣克鲁斯',
  'San Jorge': '圣约鲁吉',
  Bissau: '比绍',
  Luanda: '罗安达',
  Argin: '阿尔金岛',
  Bathurst: '巴得斯特',
  Timbuktu: '廷巴克图',
  Abidjan: '阿必尚',
  Sofala: '索法拉',
  Malindi: '马林迪',
  Mogadishu: '摩加迪休',
  Mombasa: '蒙巴萨',
  Mozambique: '莫三比克',
  Quelimane: '刻里马纳',
  Aden: '亚丁',
  Hormuz: '根布龙',
  Massawa: '马沙华',
  Cairo: '开罗',
  Basra: '巴士拉',
  Mecca: '麦加',
  Quatar: '卡塔尔',
  Shiraz: '设拉福',
  Muscat: '马斯开特',
  Diu: '迪普',
  Cochin: '柯钦',
  Ceylon: '锡兰',
  Amboa: '安波那',
  Goa: '果阿',
  Malacca: '麻六甲',
  Ternate: '德那第',
  Banda: '班达',
  Dili: '帝力',
  Pasei: '巴赛',
  Sunda: '巽他',
  Calicut: '科泽科德',
  Bankao: '邦加',
  Zeiton: '泉州',
  Macao: '澳门',
  Hanoi: '河内',
  Changan: '长安',
  Sakai: '界',
  Nagasaki: '长崎',
  Hekla: '赫努克',
  Narvik: '纳尔维',
  'Cape Town': '开普敦',
  Belgrade: '贝尔格勒',
  Tamatave: '塔马达夫',
  Dikson: '狄克孙',
  Lushun: '旅顺',
  Leveque: '来巴求',
  Mindanao: '棉兰老',
  Tiksi: '提克西',
  Ezo: '北海道',
  Geelong: '季窿',
  Guam: '关岛',
  Moresby: '莫尔兹比',
  Korf: '科尔夫',
  Wanganui: '惠灵顿',
  Suva: '苏瓦',
  Nome: '诺母',
  Naalehu: '欧胡',
  Tahiti: '塔希提',
  Juneau: '朱诺',
  Coppermine: '巴伊阿',
  'Santa Barbara': '圣大巴尔巴拉',
  Churchill: '邱吉尔',
  Callao: '卡亚俄',
  Valparaiso: '法耳巴拉索',
  Mollendo: '摩伦多',
  'Cape Cod': '圣约翰',
  Montevideo: '蒙得维的亚',
  Forel: '法维尔',
  Europe: '欧洲',
  'New World': '新大陆',
  'West Africa': '西非',
  'East Africa': '东非',
  'Middle East': '中东',
  India: '印度',
  'Southeast Asia': '东南亚',
  'Far East': '远东',
  Iberia: '伊比利亚',
  'Northern Europe': '北欧',
  'The Mediterranean': '地中海',
  'North Africa': '北非',
  'Ottoman Empire': '奥斯曼帝国',
  'Central America': '中美洲',
  'South America': '南美洲',
  'Supply port': '补给港',
  Wheat: '小麦',
  Salt: '盐',
  Wine: '葡萄酒',
  'Olive Oil': '橄榄油',
  Sugar: '砂糖',
  Cotton: '棉花',
  Wool: '羊毛',
  Silk: '丝绸',
  Dye: '染料',
  Pepper: '胡椒',
  Cinnamon: '肉桂',
  Cloves: '丁香',
  Nutmeg: '肉豆蔻',
  Gold: '黄金',
  Silver: '白银',
  Ivory: '象牙',
  Copper: '铜',
  Iron: '铁',
  Lumber: '木材',
  Tea: '茶',
  Porcelain: '瓷器',
  Glassware: '玻璃器',
  Coffee: '咖啡',
  Fur: '毛皮',
  Food: '食物',
  Beverage: '饮料',
  Textile: '纺织品',
  Spice: '香料',
  Mineral: '矿产',
  Material: '原料',
  Luxury: '奢侈品',
  Specialty: '特产',
  'João Franco': '约翰·法雷尔',
  João: '约翰',
  'Otto Baynes': '奥托·斯宾诺拉',
  'Ernst von Bohr': '恩斯特·洛佩斯',
  'Pietro Conti': '皮耶德·康迪',
  'Ali Vezas': '阿兰·维斯特',
  'Rocco Alemkel': '洛克·阿尔姆克',
  'Old Sea Hand Rocco': '老水手洛克',
  'Enrico Malione': '恩里克·马里奥内',
  'Brother Enrico': '恩里克神父',
  'Duke Franco': '法雷尔公爵',
  'Duchess Christiana': '克里斯蒂安娜公爵夫人',
  'Butler Marco': '管家马可',
  'Carlotta, Owner of the Pub': '酒吧老板卡洛塔',
  'Lucia the Waitress': '女侍路琪亚',
  'Strait of Gibraltar': '直布罗陀海峡',
  'The Azores': '亚速尔群岛',
  'Cape Bojador': '博哈多尔角',
  'Cape Verde': '佛得角',
  'Cape São Roque': '圣罗克角',
  'Bab-el-Mandeb': '曼德海峡',
  'Strait of Hormuz': '霍尔木兹海峡',
  'Mouth of the Amazon': '亚马逊河口',
  'Cape Comorin': '科摩林角',
  'Strait of Malacca': '马六甲海峡',
  'The Galápagos Islands': '加拉帕戈斯群岛',
  'Cape of Good Hope': '好望角',
  'The Bering Strait': '白令海峡',
  'Strait of Magellan': '麦哲伦海峡',
  Balsa: '轻木帆船',
  'Hansa Cog': '单桅帆船',
  Dhow: '单桅三角帆船',
  Buss: '多桅帆船',
  Tallette: '三角帆船',
  'Caravela Latina': '多桅三角帆船',
  'Caravela Redonda': '多桅横帆船',
  Brigantine: '多桅小型帆船',
  Nao: '中型帆船',
  Carrack: '武装帆船',
  Galleon: '西班牙大帆船',
  Xebec: '三桅帆船',
  Pinnace: '轻型帆船',
  Sloop: '单桅快船',
  Frigate: '武装快船',
  Barge: '三桅大型帆船',
  'Full-rigged Ship': '大型轮船',
  Junk: '中国式帆船',
  'Light Galley': '轻型三角帆船',
  'Flemish Galleon': '佛兰德帆船',
  'Venetian Galeass': '威尼斯炮舰',
  'La Reale': '混合式快船',
  Tekkousen: '铁甲船',
  Atakabune: '安宅船',
  Kansen: '关船',
  Dagger: '匕首',
  'Short Sword': '短剑',
  'Long Sword': '长剑',
  Rapier: '刺剑',
  Epee: '重剑',
  Estock: '破甲剑',
  'Short Saber': '短骑兵刀',
  Scimitar: '弯刀',
  'Japanese Sword': '日本刀',
  Cutlass: '水手刀',
  'Broad Sword': '阔剑',
  'Blue Crescent': '青龙偃月刀',
  Flamberge: '焰形剑',
  'Basterd Sword': '手半剑',
  Claymore: '苏格兰大剑',
  Saber: '骑兵刀',
  'Leather Armor': '皮甲',
  'Chain Mail': '锁子甲',
  'Half Plate': '半身板甲',
  'Plate Mail': '板链甲',
  Quadrant: '四分仪',
  Sextant: '六分仪',
  Theodolite: '经纬仪',
  'Pocket Watch': '怀表',
  Telescope: '望远镜',
  Cat: '猫',
  'Golden Dragon': '金龙',
  'Marque (P)': '私掠许可证（葡）',
  'Marque (S)': '私掠许可证（西）',
  'Marque (O)': '私掠许可证（奥）',
  'Marque (E)': '私掠许可证（英）',
  'Marque (I)': '私掠许可证（意）',
  'Marque (H)': '私掠许可证（荷）',
  'Tax Permit (P)': '免税证（葡）',
  'Tax Permit (S)': '免税证（西）',
  'Tax Permit (O)': '免税证（奥）',
  'Tax Permit (E)': '免税证（英）',
  'Tax Permit (I)': '免税证（意）',
  'Tax Permit (H)': '免税证（荷）',
  'Rat Poison': '鼠药',
  Balm: '香膏',
  'Lime Juice': '青柠汁',
  'Royal Crown': '王冠',
  'Silk Shawl': '丝绸披肩',
  'China Dress': '中国礼服',
  'Aqua Tiara': '海蓝宝石冠',
  'Platinum Comb': '白金梳',
  'Ermine Coat': '貂皮大衣',
  Circlet: '宝石头环',
  'Peacock Fan': '孔雀扇',
  'Silk Scarf': '丝巾',
  'Velvet Coat': '天鹅绒大衣',
  'Diamond Crown': '钻石王冠',
  'Mermaid Bangle': '人鱼手镯',
  'Ruby Scepter': '红宝石权杖',
  Candleholder: '烛台',
  'Jade Jewelbox': '翡翠珠宝盒',
  'Crown of Glory': '荣耀之冠',
  'Gold Bracelet': '金手镯',
  'Sapphire Ring': '蓝宝石戒指',
  'Malachite Box': '孔雀石盒',
  'Garnet Brooch': '石榴石胸针',
  'Ruby Ring': '红宝石戒指',
  'Magic Muramasa': '妖刀村正',
  'Rune Blade': '如尼剑',
  'Crusader Armor': '十字军铠甲',
  'Crusader Sword': '十字军剑',
  'Siva’s Sword': '湿婆之剑',
  'Errol’s Plate': '艾罗尔板甲',
  'Straight Sword': '直剑',
  'Fencing Sword': '刺剑',
  'Curved Sword': '弯刀',
  'Heavy Sword': '重剑',
  Armor: '防具',
  'Measuring Instrument': '测量仪器',
  'Voyager’s Aid': '航海用品',
  'Emergency Item': '应急用品',
  Accessory: '饰品',
  Treasure: '宝物',
  'Celestial Navigation': '测量',
  Accounting: '会计',
  Negotiation: '交涉',
  Gunnery: '炮术',
  Cartography: '绘图',
  ...descriptions,
};

export default terms;
