export const ui: Record<string, string> = {
  System: '系统',
  Save: '保存',
  Load: '读取',
  Reset: '重置',
  Language: '语言',
  'Confirm Reset?': '确认重置？',
  'Day {day}': '航海第 {day} 天',
  Ingots: '金锭',
  Coins: '金币',
  Mates: '伙伴',
  Fleet: '舰队',
  Items: '物品',
  Discoveries: '发现',
  Adventure: '冒险名声',
  Pirate: '海盗名声',
  Trade: '贸易名声',
  Provisions: '补给',
  Wind: '风',
  Current: '洋流',
  'Your fleet': '我方舰队',
  knots: '节',
  Economy: '经济',
  Investment: '投资',
  Industry: '工业',
  'Price Index': '价格指数',
  Market: '交易所',
  Pub: '酒吧',
  Shipyard: '船厂',
  Harbor: '港口',
  Lodge: '旅店',
  Palace: '王宫',
  Guild: '工会',
  Misc: '其他',
  Bank: '银行',
  'Item Shop': '道具店',
  Church: '教堂',
  'Fortune Teller': '占卜屋',
  'Buy Goods': '购买商品',
  'Sell Goods': '出售商品',
  Invest: '投资',
  'Market Rate': '市场行情',
  'Recruit Crew': '招募水手',
  'Dismiss Crew': '解雇水手',
  Treat: '请客',
  Meet: '会见',
  Waitress: '女侍',
  Gamble: '赌博',
  'New Ship': '购买新船',
  'Used Ship': '购买旧船',
  Repair: '修理',
  Sell: '出售',
  Remodel: '改造',
  Sail: '出航',
  Supply: '补给',
  Moor: '停泊',
  'Check In': '住店',
  Gossip: '打听消息',
  'Port Info': '港口情报',
  'Meet Ruler': '谒见国王',
  Defect: '转籍',
  Ship: '船只',
  'Job Assignment': '接受任务',
  'Country Info': '国家情报',
  Deposit: '存款',
  Withdraw: '取款',
  Borrow: '借款',
  Repay: '还款',
  Buy: '购买',
  Pray: '祈祷',
  Donate: '捐献',
  Life: '命运',
  Career: '事业',
  Love: '恋爱',
  Yes: '是',
  No: '否',
  Submit: '确定',
  Qty: '数量',
  Item: '物品',
  'Ship Model': '船型',
  'Your Ships': '我方船只',
  Crew: '水手',
  'Cargo Load': '载量',
  Water: '水',
  Food: '食物',
  Shot: '炮弹',
  Durability: '耐久度',
  Tacking: '转向力',
  Power: '推进力',
  Capacity: '容量',
  Cargo: '货舱',
  'Guns (Max/Remodel)': '火炮（最大/改造）',
  'Crew (Min/Max)': '水手（最低/当前）',
  'Max Crew (Remodel)': '最大水手（改造）',
  Rank: '爵位',
  None: '无',
  Wages: '薪金',
  'Navigation Level': '航海等级',
  'Battle Level': '战斗等级',
  Experience: '经验',
  Skills: '技能',
  leadership: '统御',
  seamanship: '航海术',
  knowledge: '知识',
  intuition: '直觉',
  courage: '勇气',
  swordplay: '剑术',
  charm: '魅力',
  luck: '运气',
  'Loyal to Portugal': '效忠葡萄牙',
  'Age {age}': '{age} 岁',
  'You have no items.': '你没有任何物品。',
  'You have no discoveries.': '你还没有任何发现。',
  '+{fame} adventure fame, +{gold}g': '冒险名声 +{fame}，金币 +{gold}',
  'Discovered: {name} — +{fame} adventure fame, +{gold}g':
    '发现：{name} — 冒险名声 +{fame}，金币 +{gold}',
  N: '北',
  S: '南',
  E: '东',
  W: '西',
  'Game saved.': '游戏已保存。',
  'Game loaded.': '存档已读取。',
  'Failed to load save.': '读取存档失败。',
  'No save data found.': '未找到存档。',
  'Click Reset again to confirm.': '再次点击“重置”以确认。',
  'This feature is not implemented yet. Press ESC to exit this building.':
    '此功能尚未实现。按 ESC 键离开这座建筑。',
  Goods: '商品',
  goods: '商品',
  '{name} at {price}g each. How many?': '{name}每份 {price} 金币。要多少？',
  '{quantity} {name} for {total}g. Deal?':
    '{quantity} 份{name}，共 {total} 金币。成交吗？',
  'Abundant (cheap): {supply}\nScarce (expensive): {demand}':
    '供应充足（便宜）：{supply}\n供应紧缺（昂贵）：{demand}',
  'Supplies exhausted': '补给已耗尽',
  'Less than 1 day remaining': '补给不足 1 天',
  'Only {days} day remaining': '补给仅够 {days} 天',
  'Only {days} days remaining': '补给仅够 {days} 天',
  '{days} days remaining': '补给可用 {days} 天',
  'Lost {deaths} crew member to starvation': '{deaths} 名水手因饥饿死亡',
  'Lost {deaths} crew members to starvation': '{deaths} 名水手因饥饿死亡',
  '{lost} — the fleet drifted into port': '{lost}——舰队漂流进港',
  'Welcome to the market. What can I do for you?':
    '欢迎来到交易所。有什么可以帮您？',
  "You don't have any gold.": '你身上没有金币。',
  'Your ships have no cargo space available.': '你的船已没有空余货舱。',
  'Take a look at our wares.': '请看看我们的货物。',
  'Anything else catch your eye?': '还有什么看中的吗？',
  "You don't have any trade goods to sell.": '你没有可出售的商品。',
  'What are you selling?': '想卖什么？',
  'Got anything else?': '还有别的吗？',
  'May I help you?': '有什么可以帮您？',
  'I’m sure you’ll find something you like.': '一定有您中意的东西。',
  'Are you interested in anything else?': '还有其他感兴趣的吗？',
  'It seems you have no gold.': '看来你没有金币。',
  'You don’t have any items.': '你没有任何物品。',
  'What would you like to sell?': '想卖什么？',
  'What else can you sell me?': '还有什么可以卖给我？',
  'Welcome to our regional branch of the Marco Polo Bank.':
    '欢迎光临马可·波罗银行分行。',
  'You don’t have any gold to deposit.': '你没有可存入的金币。',
  'You don’t have any gold in your account.': '你的账户中没有金币。',
  'With your poor credit history, there’s no way we can give you a loan.':
    '你的信用记录太差，我们无法放贷。',
  'You don’t owe us any money.': '你没有欠款。',
  'You don’t have any gold to pay back your loan with.': '你没有金币可以还款。',
  'Thank you for your payment.': '感谢您的还款。',
  'Well, that takes care of your debt! Thank you for using Marco Polo Bank.':
    '债务已经全部结清！感谢使用马可·波罗银行。',
  'Thank you for choosing Marco Polo Bank.': '感谢选择马可·波罗银行。',
  'Hey sailor, you’ll like our wine!': '嗨，水手！你会喜欢我们的酒！',
  'We have enough men in our crew.': '我们的水手已经够多了。',
  'We don’t have enough gold.': '我们的金币不够。',
  'Shall we recruit some men for our crew?': '要为舰队招募一些水手吗？',
  'Hey! Do any of you tough sailors want to join our crew?':
    '嗨！有哪位好手愿意加入我们的舰队？',
  'We rounded up {count} men, at the cost of {cost} gold pieces.':
    '招募到 {count} 名水手，共花费 {cost} 金币。',
  'Welcome to our church.': '欢迎来到教堂。',
  'Let’s pray that God will protect you.': '让我们祈求上帝保佑你。',
  'Thank you for your generous donation. Our heavenly father will surely watch over you.':
    '感谢您慷慨的捐献。天父定会看顾您。',
  'Come visit us again.': '欢迎再来。',
  'May God bless you in your travels!': '愿上帝保佑您的旅途！',
  'I respect your interest, but Christians are not allowed in the house of Allah.':
    '我尊重您的诚意，但基督徒不得进入真主的殿堂。',
  'You have no gold.': '你身上没有金币。',
  'Your money will be used to feed the poor. How much can you give?':
    '捐款将用于救济穷人。你愿意捐多少？',
  'Welcome. You must be tired. Please make yourself at home.':
    '欢迎光临。一路辛苦了，请好好休息。',
  'Ahoy there, matey, will ye be shoving off?': '喂，伙计，要出航了吗？',
  'We’ll starve if we leave with no provisions!':
    '没有补给就出航，我们会饿死的！',
  'Some ships have no crew assigned. We won’t get anywhere.':
    '有些船还没有配置水手，无法出航。',
  'We won’t be able to sail for long. Shall we cast off anyway?':
    '现有补给无法支撑太久。仍要出航吗？',
  'We can sail for {days} days. Shall we cast off?':
    '补给可供航行 {days} 天。要出航吗？',
  "I'm afraid you can't buy that many.": '恐怕你买不了这么多。',
  'Gold Funding': '领取资金',
  'What brings you to this shipyard?': '来船厂有什么事？',
  'I’m afraid you don’t have enough gold.': '恐怕你的金币不够。',
  'You don’t have a sailor available to captain this ship.':
    '你没有可以指派为船长的水手。',
  'All right, it’s yers. Time to name yer ship.':
    '好了，它是你的了。给新船取个名字吧。',
  'Your fleet’s already in tiptop shape, matey!':
    '你的舰队状态已经再好不过了！',
  'We only have the flag ship.': '我们只有旗舰。',
  'Which one is for sale?': '要卖哪一艘？',
  'Ship name?': '船名是？',
  'The {name} will cost you {price} gold pieces.': '{name}售价 {price} 金币。',
  'I’d like to take that {name} off your hands. I’ll take it for {price} gold pieces.':
    '这件{name}我愿出 {price} 金币收购。',
  'I’d sell this ship for {price} gold pieces. What do ye say?':
    '这艘船售价 {price} 金币。怎么样？',
  'For this ship, I’ll give you {price} gold pieces. OK?':
    '这艘船我出 {price} 金币。可以吗？',
  'Water is free. How many barrels should we load?': '淡水免费。要装多少桶？',
  'Food will cost us {price} gold pieces per barrel. How many barrels will we buy?':
    '食物每桶 {price} 金币。要买多少桶？',
  'Lumber will cost us {price} gold pieces per plank. How many planks will we buy?':
    '木材每块 {price} 金币。要买多少块？',
  'Cannonballs will cost us {price} gold pieces per barrel. How many barrels will we buy?':
    '炮弹每桶 {price} 金币。要买多少桶？',
  'Navigator of {ship}': '{ship}号航海士',
  'First Mate of {ship}': '{ship}号助手',
  'Bookkeeper of {ship}': '{ship}号会计',
  'Chief Navigator of {ship}': '{ship}号水手长',
  'Commodore of {ship}': '{ship}号提督',
  'Captain of {ship}': '{ship}号船长',
  'Now you have {amount} gold pieces in your savings account.':
    '你的账户现有 {amount} 金币。',
  'How much would you like to deposit? (0-{limit})':
    '要存入多少？（0–{limit}）',
  'We’ll deposit {amount} gold pieces into your account. The monthly interest rate is 3%':
    '将 {amount} 金币存入账户。月利率为 3%。',
  'How much would you like to withdraw? (0-{limit})':
    '要取出多少？（0–{limit}）',
  'Here is {amount} gold from your account.':
    '这是从账户取出的 {amount} 金币。',
  'Your credit line is {amount} gold pieces.': '你的借款额度为 {amount} 金币。',
  'How much gold do you need to borrow? (0-{limit})':
    '要借多少金币？（0–{limit}）',
  'Then we’ll lend you {amount} gold pieces.':
    '那么我们将借给你 {amount} 金币。',
  'Now your debt is {amount} gold.': '你现在负债 {amount} 金币。',
  'How much of your loan will you be paying back? (0-{limit})':
    '要偿还多少借款？（0–{limit}）',
  'The monthly interest rate is 10%. Please invest our loan wisely.':
    '月利率为 10%。请善用这笔借款。',
};

export default ui;
